## This notebook builds a combined dataset that links Airbnb listing data with Bond market rent data by location and time.

In [1]:
import pandas as pd

## Loading the source data
The notebook reads:
- `cleaned_dataset_bond.csv` → Bond data (rental market information)

In [2]:
df_tnc= pd.read_csv("../Output/cleaned_dataset_bond.csv")

In [3]:
df_tnc.sample(5)

,TimeFrame,Location Id,Dwelling Type,Number Of Beds,Total Bonds,Active Bonds,Closed Bonds,Median Rent,Geometric Mean Rent,Upper Quartile Rent,Lower Quartile Rent,Log Std Dev Weekly Rent
23228,2025-10-01,178100.0,House,1,6,15,0,585.0,534.0,684.0,478.0,0.3376
5888,2026-04-01,170802.0,House,2,6,9,3,528.0,527.0,545.0,510.0,0.0540
18037,2025-10-01,198400.0,ALL,1,6,33,3,535.0,482.0,603.0,393.0,0.3076
20135,2025-10-01,111700.0,ALL,ALL,24,267,12,623.0,604.0,713.0,543.0,0.1931
10119,2026-01-01,352000.0,Apartment,4,6,9,0,413.0,406.0,614.0,260.0,0.5860

In [4]:
df_tnc.info()

<class 'pandas.DataFrame'>
RangeIndex: 26991 entries, 0 to 26990
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TimeFrame                26991 non-null  str
 1   Location Id              26991 non-null  float64
 2   Dwelling Type            26991 non-null  str
 3   Number Of Beds           26133 non-null  str
 4   Total Bonds              26991 non-null  int64
 5   Active Bonds             26991 non-null  int64
 6   Closed Bonds             26991 non-null  int64
 7   Median Rent              26991 non-null  float64
 8   Geometric Mean Rent      26991 non-null  float64
 9   Upper Quartile Rent      26991 non-null  float64
 10  Lower Quartile Rent      26991 non-null  float64
 11  Log Std Dev Weekly Rent  26991 non-null  float64
dtypes: float64(6), int64(3), str(3)
memory usage: 2.5 MB

## Loading the source data
The notebook reads:
- `christ_new_filt.csv` → cleaned Airbnb data with geolocation and listing dates

In [5]:
christ_clean= pd.read_csv("../Output/christ_new_filt.csv")

In [6]:
christ_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 26369 entries, 0 to 26368
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              26369 non-null  int64
 1   name                            26369 non-null  str
 2   host_id                         26369 non-null  float64
 3   host_name                       26368 non-null  str
 4   neighbourhood_group             26369 non-null  str
 5   neighbourhood                   26369 non-null  str
 6   latitude                        26369 non-null  float64
 7   longitude                       26369 non-null  float64
 8   room_type                       26369 non-null  str
 9   price                           24478 non-null  float64
 10  minimum_nights                  26360 non-null  float64
 11  number_of_reviews               26369 non-null  int64
 12  last_review                     24068 non-null  str
 13  reviews_per_month               24068 non-null  str
 14  calculated_host_listings_count  26369 non-null  float64
 15  availability_365                26369 non-null  int64
 16  number_of_reviews_ltm           26369 non-null  int64
 17  Pub_date                        26369 non-null  str
 18  Difference_date                 24068 non-null  float64
 19  month_name                      26369 non-null  str
 20  year                            26369 non-null  int64
dtypes: float64(7), int64(5), str(9)
memory usage: 4.2 MB

In [7]:
christ_clean.sample(10)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,Pub_date,Difference_date,month_name,year
20072,1582329029751274493,Roomy 3-Bed Harbour View Getaway · Sleeps 7,20665858.0,Adam,Christchurch City,Banks Peninsula Ward,-43.758760,172.946420,Entire home/apt,425.0,...,13,2026-06-06,1970-01-01 00:00:00.000000002,23.0,350,13,2026-07-12,36.0,July,2026
2478,1291521865463376119,Luxury 2Bed2Bath Standalone Home With Parking,49642171.0,Xihang,Christchurch City,Fendalton Ward,-43.506473,172.623183,Entire home/apt,159.0,...,18,2025-09-30,1970-01-01 00:00:00.000000001,88.0,325,18,2025-10-07,7.0,October,2025
7850,1211070132323635531,Eco Spa-bath Studio,179297759.0,Peng,Christchurch City,Riccarton Ward,-43.538437,172.578953,Private room,158.0,...,9,2025-12-19,1970-01-01 00:00:00.000000000,19.0,364,1,2026-03-17,88.0,March,2026
19067,1673584994290815525,Spacious CBD Family Townhouse | Stadium + Parking,482671075.0,Care Property Stays,Christchurch City,Central Ward,-43.534078,172.641487,Entire home/apt,304.0,...,4,2026-06-09,1970-01-01 00:00:00.000000002,175.0,177,4,2026-06-19,10.0,June,2026
24909,1189492206407986371,Beautiful room in quiet oasis,8899806.0,Tanya,Christchurch City,Cashmere Ward,-43.554237,172.651471,Private room,109.0,...,8,2026-08-01,1970-01-01 00:00:00.000000000,1.0,178,2,2026-08-13,12.0,August,2026
22721,39112242,Stylish Pool House - Pet friendly,299816018.0,Philippa,Christchurch City,Cashmere Ward,-43.554460,172.658330,Entire home/apt,229.0,...,159,2026-07-06,1970-01-01 00:00:00.000000001,2.0,133,5,2026-07-12,6.0,July,2026
8550,1465045141748734584,Studio cozy room close to Airport,380744891.0,Kelly,Christchurch City,Waimairi Ward,-43.500838,172.564877,Entire home/apt,120.0,...,15,2026-02-21,1970-01-01 00:00:00.000000001,1.0,41,15,2026-03-17,24.0,March,2026
2633,48247285,Central City 2 Bedroom Apartment with easy car...,389301058.0,Rod,Christchurch City,Central Ward,-43.527550,172.632470,Entire home/apt,157.0,...,82,2025-07-05,1970-01-01 00:00:00.000000001,1.0,148,22,2025-10-07,94.0,October,2025
14714,1543394950742402693,Seaview Family Stay Akaroa,24205506.0,"Mayie, Judi And Karen At Bookahome",Christchurch City,Banks Peninsula Ward,-43.810190,172.961740,Entire home/apt,300.0,...,8,2026-04-26,1970-01-01 00:00:00.000000001,83.0,337,8,2026-05-23,27.0,May,2026
17199,1296842241519010281,298 Home 4BR CBD with Free Parking,248111275.0,Winnie,Christchurch City,Central Ward,-43.529964,172.645859,Entire home/apt,512.0,...,3,2025-09-14,1970-01-01 00:00:00.000000000,2.0,105,1,2026-06-19,278.0,June,2026

## Checking and cleaning the data
It inspects the tables to confirm columns, row counts, and data types. It also checks for duplicate coordinates and duplicate records.

In [8]:
coordinates = christ_clean[["latitude", "longitude"]].drop_duplicates()

print("Total rows:", len(christ_clean))
print("Unique latitude + longitude pairs:", len(coordinates))

Total rows: 26369
Unique latitude + longitude pairs: 4053

In [9]:
print(
    christ_clean[["latitude", "longitude"]].duplicated().sum()
)

22316

## Enriching listings with area codes
Airbnb listings have latitude and longitude. The notebook uses the Koordinates API to map each coordinate to a geographic area code (such as a statistical area ID). This generates an `area_code` for each Airbnb listing.

In [10]:
# import requests
# import pandas as pd
# import time

# API_KEY = "819797b85c5949fdb5a1dbc4cd468409"
# LAYER_ID = 123515
# URL = "https://koordinates.com/services/query/v1/vector.json"

# # Get unique coordinates
# coordinates = (
#     christ_clean[["latitude", "longitude"]]
#     .drop_duplicates()
#     .reset_index(drop=True)
# )

# print("Unique coordinates:", len(coordinates))

# area_codes = []

# start_time = time.time()

# for i, row in coordinates.iterrows():

#     latitude = row["latitude"]
#     longitude = row["longitude"]

#     params = {
#         "key": API_KEY,
#         "layer": LAYER_ID,
#         "x": longitude,
#         "y": latitude,
#         "max_results": 1,
#         "radius": 0,
#         "with_field_names": "true"
#     }

#     try:
#         response = requests.get(
#             URL,
#             params=params,
#             timeout=30
#         )

#         if response.status_code == 200:

#             data = response.json()

#             features = (
#                 data["vectorQuery"]
#                 ["layers"][str(LAYER_ID)]
#                 ["features"]
#             )

#             if features:
#                 area_code = features[0]["properties"].get(
#                     "SA22026_V1_00"
#                 )
#             else:
#                 area_code = None

#         else:
#             print("Error:", response.status_code)
#             area_code = None

#     except Exception as e:
#         print("Error:", e)
#         area_code = None

#     area_codes.append(area_code)

#     # Show progress every 100 requests
#     if (i + 1) % 100 == 0:
#         elapsed = time.time() - start_time
#         print(
#             f"{i + 1} / {len(coordinates)} completed "
#             f"({elapsed / 60:.1f} minutes)"
#         )

# print("Finished!")

# coordinates["area_code"] = area_codes

In [11]:
christ_clean.head(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,Pub_date,Difference_date,month_name,year
0,40183765,Ensuite Cabin (Sleeps 6),98758734.0,North South Holiday Park,Christchurch City,Harewood Ward,-43.470020,172.570880,Private room,NaN,...,0,NaN,NaN,20.0,317,0,2025-10-07,NaN,October,2025
1,1149729199964166318,Handy city center. Simple room,298456605.0,Tony,Christchurch City,Central Ward,-43.532700,172.664030,Private room,NaN,...,25,2025-07-15,1970-01-01 00:00:00.000000001,6.0,0,21,2025-10-07,84.0,October,2025
2,1097487,Heritage Magic in Merivale,4993285.0,Paulette,Christchurch City,Fendalton Ward,-43.511490,172.625400,Private room,166.0,...,230,2025-03-03,1970-01-01 00:00:00.000000002,1.0,221,14,2025-10-07,218.0,October,2025
3,1339647508906377362,Settle into the sun set,54299306.0,Sarena,Christchurch City,Burwood Ward,-43.482864,172.668660,Entire home/apt,NaN,...,2,2025-04-26,1970-01-01 00:00:00.000000000,1.0,0,2,2025-10-07,164.0,October,2025
4,1211070132323635531,Eco Spa-bath Studio,179297759.0,Peng,Christchurch City,Riccarton Ward,-43.538437,172.578953,Private room,126.0,...,8,2025-03-01,1970-01-01 00:00:00.000000000,20.0,359,5,2025-10-07,220.0,October,2025

## Saving the file with new area_coloumn added to it

In [12]:
#christ_clean.to_csv("../Output/christ_area_codes.csv", index=False)

In [13]:
christ_clean.head(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,Pub_date,Difference_date,month_name,year
0,40183765,Ensuite Cabin (Sleeps 6),98758734.0,North South Holiday Park,Christchurch City,Harewood Ward,-43.470020,172.570880,Private room,NaN,...,0,NaN,NaN,20.0,317,0,2025-10-07,NaN,October,2025
1,1149729199964166318,Handy city center. Simple room,298456605.0,Tony,Christchurch City,Central Ward,-43.532700,172.664030,Private room,NaN,...,25,2025-07-15,1970-01-01 00:00:00.000000001,6.0,0,21,2025-10-07,84.0,October,2025
2,1097487,Heritage Magic in Merivale,4993285.0,Paulette,Christchurch City,Fendalton Ward,-43.511490,172.625400,Private room,166.0,...,230,2025-03-03,1970-01-01 00:00:00.000000002,1.0,221,14,2025-10-07,218.0,October,2025
3,1339647508906377362,Settle into the sun set,54299306.0,Sarena,Christchurch City,Burwood Ward,-43.482864,172.668660,Entire home/apt,NaN,...,2,2025-04-26,1970-01-01 00:00:00.000000000,1.0,0,2,2025-10-07,164.0,October,2025
4,1211070132323635531,Eco Spa-bath Studio,179297759.0,Peng,Christchurch City,Riccarton Ward,-43.538437,172.578953,Private room,126.0,...,8,2025-03-01,1970-01-01 00:00:00.000000000,20.0,359,5,2025-10-07,220.0,October,2025

In [14]:
christ_area= pd.read_csv("../Output/christ_area_codes.csv")

In [15]:
christ_area.head(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,Pub_date,Difference_date,month_name,year,area_code
0,40183765,Ensuite Cabin (Sleeps 6),98758734.0,North South Holiday Park,Christchurch City,Harewood Ward,-43.470020,172.570880,Private room,NaN,...,NaN,NaN,20.0,317,0,2025-11-07,NaN,November,2025,316700
1,1149729199964166318,Handy city center. Simple room,298456605.0,Tony,Christchurch City,Central Ward,-43.532700,172.664030,Private room,NaN,...,2025-07-15,1970-01-01 00:00:00.000000001,6.0,0,21,2025-11-07,115.0,November,2025,327902
2,1097487,Heritage Magic in Merivale,4993285.0,Paulette,Christchurch City,Fendalton Ward,-43.511490,172.625400,Private room,166.0,...,2025-03-03,1970-01-01 00:00:00.000000002,1.0,221,14,2025-11-07,249.0,November,2025,322200
3,1339647508906377362,Settle into the sun set,54299306.0,Sarena,Christchurch City,Burwood Ward,-43.482864,172.668660,Entire home/apt,NaN,...,2025-04-26,1970-01-01 00:00:00.000000000,1.0,0,2,2025-11-07,195.0,November,2025,321302
4,1211070132323635531,Eco Spa-bath Studio,179297759.0,Peng,Christchurch City,Riccarton Ward,-43.538437,172.578953,Private room,126.0,...,2025-03-01,1970-01-01 00:00:00.000000000,20.0,359,5,2025-11-07,251.0,November,2025,322700

In [16]:
df_tnc.sample(5)

,TimeFrame,Location Id,Dwelling Type,Number Of Beds,Total Bonds,Active Bonds,Closed Bonds,Median Rent,Geometric Mean Rent,Upper Quartile Rent,Lower Quartile Rent,Log Std Dev Weekly Rent
11441,2026-01-01,230300.0,ALL,ALL,18,234,24,575.0,529.0,648.0,453.0,0.2592
4315,2026-04-01,149800.0,Apartment,ALL,6,15,0,520.0,527.0,530.0,518.0,0.0413
22592,2025-10-01,244100.0,Flat,1,6,93,3,350.0,366.0,388.0,350.0,0.0690
14718,2026-01-01,362200.0,ALL,1,9,24,0,530.0,521.0,540.0,520.0,0.1036
22836,2025-10-01,235500.0,Flat,ALL,6,51,6,395.0,386.0,420.0,366.0,0.2010

In [17]:
# print(christ_area["area_code"].dtype)
# print(df_tnc["location id"].dtype)

## Standardizing key identifiers
The notebook converts and renames columns so the two datasets use the same naming convention for:
- `area_code`
- `TimeFrame`

In [18]:
# df_tnc["location id"] = (
#     df_tnc["location id"]
#     .astype("Int64")
#     .astype("string")
# )

In [19]:
print(df_tnc["Location Id"].head())
print(df_tnc["Location Id"].dtype)

0    100100.0
1    100600.0
2    100700.0
3    100800.0
4    101100.0
Name: Location Id, dtype: float64
float64

## Renaming the Location ID coloumn to area_code to both Air BNB and bond data coloumn could match

In [20]:
df_tnc = df_tnc.rename(columns={"Location Id": "area_code"})

In [21]:
df_tnc.info()

<class 'pandas.DataFrame'>
RangeIndex: 26991 entries, 0 to 26990
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TimeFrame                26991 non-null  str
 1   area_code                26991 non-null  float64
 2   Dwelling Type            26991 non-null  str
 3   Number Of Beds           26133 non-null  str
 4   Total Bonds              26991 non-null  int64
 5   Active Bonds             26991 non-null  int64
 6   Closed Bonds             26991 non-null  int64
 7   Median Rent              26991 non-null  float64
 8   Geometric Mean Rent      26991 non-null  float64
 9   Upper Quartile Rent      26991 non-null  float64
 10  Lower Quartile Rent      26991 non-null  float64
 11  Log Std Dev Weekly Rent  26991 non-null  float64
dtypes: float64(6), int64(3), str(3)
memory usage: 2.5 MB

In [22]:
# df_tnc= pd.read_csv(r"C:\Users\VISHAL\Desktop\g2\cleaned_dataset_bond.csv")

In [23]:
# christ_area= pd.read_csv(r"C:\Users\VISHAL\Desktop\g2\christ_area_codes.csv")

In [24]:
christ_area.info()

<class 'pandas.DataFrame'>
RangeIndex: 19368 entries, 0 to 19367
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              19368 non-null  int64
 1   name                            19368 non-null  str
 2   host_id                         19368 non-null  float64
 3   host_name                       19367 non-null  str
 4   neighbourhood_group             19368 non-null  str
 5   neighbourhood                   19368 non-null  str
 6   latitude                        19368 non-null  float64
 7   longitude                       19368 non-null  float64
 8   room_type                       19368 non-null  str
 9   price                           18128 non-null  float64
 10  minimum_nights                  19359 non-null  float64
 11  number_of_reviews               19368 non-null  int64
 12  last_review                     17674 non-null  str
 13  reviews_per_month               17674 non-null  str
 14  calculated_host_listings_count  19368 non-null  float64
 15  availability_365                19368 non-null  int64
 16  number_of_reviews_ltm           19368 non-null  int64
 17  Pub_date                        19368 non-null  str
 18  Difference_date                 17674 non-null  float64
 19  month_name                      19368 non-null  str
 20  year                            19368 non-null  int64
 21  area_code                       19368 non-null  int64
dtypes: float64(7), int64(6), str(9)
memory usage: 3.3 MB

## Coverting the dtype of bond dataset TimeFrame column to datetime stamp so it could match with timeframe column of Air Bnb

In [25]:
df_tnc['TimeFrame'] = pd.to_datetime(df_tnc['TimeFrame'])

In [26]:
df_tnc.info()

<class 'pandas.DataFrame'>
RangeIndex: 26991 entries, 0 to 26990
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TimeFrame                26991 non-null  datetime64[us]
 1   area_code                26991 non-null  float64
 2   Dwelling Type            26991 non-null  str
 3   Number Of Beds           26133 non-null  str
 4   Total Bonds              26991 non-null  int64
 5   Active Bonds             26991 non-null  int64
 6   Closed Bonds             26991 non-null  int64
 7   Median Rent              26991 non-null  float64
 8   Geometric Mean Rent      26991 non-null  float64
 9   Upper Quartile Rent      26991 non-null  float64
 10  Lower Quartile Rent      26991 non-null  float64
 11  Log Std Dev Weekly Rent  26991 non-null  float64
dtypes: datetime64[us](1), float64(6), int64(3), str(2)
memory usage: 2.5 MB

## Converting bond data set and Air Bnb data set area_code coloumn type into string so can match the dtype of both coloumns.

In [27]:
df_tnc["area_code"] = pd.to_numeric(
    df_tnc["area_code"], errors="coerce"
).astype("Int64")

In [28]:
christ_area["area_code"] = pd.to_numeric(
    christ_area["area_code"], errors="coerce"
).astype("Int64")

## Preparing time fields
Dates are converted into a common quarterly format:
- `Pub_date` is converted to a datetime
- `TimeFrame` is created/standardized as a quarter start date

This allows Airbnb and Bond data to be matched by:
- `area_code`
- `TimeFrame`

In [29]:
christ_area["Pub_date"] = pd.to_datetime(
    christ_area["Pub_date"]
)

christ_area["TimeFrame"] = (
    christ_area["Pub_date"]
    .dt.to_period("Q")
    .dt.start_time
)

In [30]:
christ_area.info()

<class 'pandas.DataFrame'>
RangeIndex: 19368 entries, 0 to 19367
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              19368 non-null  int64
 1   name                            19368 non-null  str
 2   host_id                         19368 non-null  float64
 3   host_name                       19367 non-null  str
 4   neighbourhood_group             19368 non-null  str
 5   neighbourhood                   19368 non-null  str
 6   latitude                        19368 non-null  float64
 7   longitude                       19368 non-null  float64
 8   room_type                       19368 non-null  str
 9   price                           18128 non-null  float64
 10  minimum_nights                  19359 non-null  float64
 11  number_of_reviews               19368 non-null  int64
 12  last_review                     17674 non-null  str
 13  reviews_per_month               17674 non-null  str
 14  calculated_host_listings_count  19368 non-null  float64
 15  availability_365                19368 non-null  int64
 16  number_of_reviews_ltm           19368 non-null  int64
 17  Pub_date                        19368 non-null  datetime64[us]
 18  Difference_date                 17674 non-null  float64
 19  month_name                      19368 non-null  str
 20  year                            19368 non-null  int64
 21  area_code                       19368 non-null  Int64
 22  TimeFrame                       19368 non-null  datetime64[us]
dtypes: Int64(1), datetime64[us](2), float64(7), int64(5), str(8)
memory usage: 3.4 MB

In [31]:
print("Dwelling Types:")
print(df_tnc["Dwelling Type"].unique())

print("\nNumber of Beds:")
print(df_tnc["Number Of Beds"].unique())

Dwelling Types:
<StringArray>
['ALL', 'Apartment', 'Boarding House', 'Flat', 'House', 'Room']
Length: 6, dtype: str

Number of Beds:
<StringArray>
['1', '2', '3', '4', '5', '9', 'ALL', '5+', nan, '6']
Length: 10, dtype: str

In [32]:
print(
    df_tnc[
        (df_tnc["Dwelling Type"] == "ALL") &
        (df_tnc["Number Of Beds"] == "ALL")
    ].shape
)

(4865, 12)

##  Filtering to the relevant Bond records
It keeps only the Bond rows where:
- `Dwelling Type == "ALL"`
- `Number Of Beds == "ALL"`

This is useful because the comparison is done at the broadest aggregate level for consistent time and area comparisons.

In [33]:
df_tnc_all = df_tnc[
    (df_tnc["Dwelling Type"] == "ALL") &
    (df_tnc["Number Of Beds"] == "ALL")
].copy()

In [34]:
print("Rows in original Bond data:", len(df_tnc))
print("Rows in ALL/ALL Bond data:", len(df_tnc_all))

Rows in original Bond data: 26991
Rows in ALL/ALL Bond data: 4865

In [35]:
duplicate_keys = df_tnc_all.duplicated(
    ["area_code", "TimeFrame"]
).sum()

print("Duplicate area_code + TimeFrame:", duplicate_keys)

Duplicate area_code + TimeFrame: 0

##  Merging datasets
The notebook merges Airbnb data with Bond data using:
- `area_code`
- `TimeFrame`

This creates a single table with Airbnb listing information plus Bond median rent and related market statistics.

In [36]:
merged_data = christ_area.merge(
    df_tnc_all,
    on=["area_code", "TimeFrame"],
    how="left",
    validate="many_to_one"
)

In [37]:
df_tnc_all.info()

<class 'pandas.DataFrame'>
Index: 4865 entries, 2446 to 21683
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TimeFrame                4865 non-null   datetime64[us]
 1   area_code                4865 non-null   Int64
 2   Dwelling Type            4865 non-null   str
 3   Number Of Beds           4865 non-null   str
 4   Total Bonds              4865 non-null   int64
 5   Active Bonds             4865 non-null   int64
 6   Closed Bonds             4865 non-null   int64
 7   Median Rent              4865 non-null   float64
 8   Geometric Mean Rent      4865 non-null   float64
 9   Upper Quartile Rent      4865 non-null   float64
 10  Lower Quartile Rent      4865 non-null   float64
 11  Log Std Dev Weekly Rent  4865 non-null   float64
dtypes: Int64(1), datetime64[us](1), float64(5), int64(3), str(2)
memory usage: 498.9 KB

## Validation and quality checks
Before exporting, the notebook verifies:
- whether the merge produced matches
- whether there are duplicate `area_code + TimeFrame` combinations
- whether the merged data contains missing values

In [38]:
print("Before merge:", len(christ_clean))
print("After merge:", len(merged_data))

Before merge: 26369
After merge: 19368

In [39]:
print(
    "Airbnb rows with Bond data:",
    merged_data["Median Rent"].notna().sum()
)

print(
    "Airbnb rows without Bond data:",
    merged_data["Median Rent"].isna().sum()
)

Airbnb rows with Bond data: 14722
Airbnb rows without Bond data: 4646

In [40]:
print(
    df_tnc_all.duplicated(
        ["area_code", "TimeFrame"]
    ).sum()
)

0

##  Saving outputs
The final merged dataset is exported as CSV files

In [41]:
merged_data.to_csv(r"../Output/christ_bond_merged.csv", index=False)


## Merged the same above data set Air Bnb and bond data set after uploading in the SQL light data base by using sqlite3 python package

In [42]:
# import sqlite3

##  Making connection with database

In [43]:
# conn = sqlite3.connect("my_database.sqlite")

In [44]:
# christ_area= pd.read_csv("../Output/christ_area_codes.csv")

In [45]:
# dataset1 = christ_area.copy()
# dataset2 = df_tnc_all.copy()

## Uplaoding the dataset in inside the SQL database

In [46]:
# dataset1.to_sql("dataset1", conn, if_exists="replace", index=False)
# dataset2.to_sql("dataset2", conn, if_exists="replace", index=False)

In [47]:
# christ_area.head(5)

## Merging the both data set in SQL Queary

In [48]:
# merged_SQL= pd.read_sql_query("""
#     SELECT
#         a.*,
#         b.*
#     FROM dataset1 AS a
#     LEFT JOIN dataset2 AS b
#         ON a.area_code = b.area_code
#         AND a.TimeFrame = b.TimeFrame
# """, conn)

In [49]:
# merged_SQL.info()