In [1]:
import pandas as pd

In [2]:
df_tnc= pd.read_csv(r"C:\Users\VISHAL\Desktop\g2\cleaned_dataset_bond.csv")

In [3]:
df_tnc.sample(5)

,TimeFrame,Location Id,Dwelling Type,Number Of Beds,Total Bonds,Active Bonds,Closed Bonds,Median Rent,Geometric Mean Rent,Upper Quartile Rent,Lower Quartile Rent,Log Std Dev Weekly Rent
14102,2026-01-01,203700.0,ALL,1,9,18,0,570.0,479.0,590.0,493.0,0.3961
22087,2025-10-01,328200.0,ALL,NaN,9,45,3,560.0,560.0,598.0,525.0,0.0905
19955,2025-10-01,164300.0,ALL,4,12,63,6,740.0,782.0,780.0,713.0,0.2053
14720,2026-01-01,362500.0,ALL,1,9,30,3,520.0,500.0,540.0,460.0,0.1095
1360,2026-04-01,136300.0,ALL,2,12,198,9,585.0,544.0,643.0,555.0,0.2796

In [4]:
df_tnc.info()

<class 'pandas.DataFrame'>
RangeIndex: 26991 entries, 0 to 26990
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TimeFrame                26991 non-null  str
 1   Location Id              26991 non-null  float64
 2   Dwelling Type            26991 non-null  str
 3   Number Of Beds           26133 non-null  str
 4   Total Bonds              26991 non-null  int64
 5   Active Bonds             26991 non-null  int64
 6   Closed Bonds             26991 non-null  int64
 7   Median Rent              26991 non-null  float64
 8   Geometric Mean Rent      26991 non-null  float64
 9   Upper Quartile Rent      26991 non-null  float64
 10  Lower Quartile Rent      26991 non-null  float64
 11  Log Std Dev Weekly Rent  26991 non-null  float64
dtypes: float64(6), int64(3), str(3)
memory usage: 2.5 MB

In [5]:
christ_clean= pd.read_csv(r"C:\Users\VISHAL\Desktop\g2\christ_new_filt.csv")

In [6]:
christ_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 19368 entries, 0 to 19367
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              19368 non-null  int64
 1   name                            19368 non-null  str
 2   host_id                         19368 non-null  float64
 3   host_name                       19367 non-null  str
 4   neighbourhood_group             19368 non-null  str
 5   neighbourhood                   19368 non-null  str
 6   latitude                        19368 non-null  float64
 7   longitude                       19368 non-null  float64
 8   room_type                       19368 non-null  str
 9   price                           18128 non-null  float64
 10  minimum_nights                  19359 non-null  float64
 11  number_of_reviews               19368 non-null  int64
 12  last_review                     17674 non-null  str
 13  reviews_per_month               17674 non-null  str
 14  calculated_host_listings_count  19368 non-null  float64
 15  availability_365                19368 non-null  int64
 16  number_of_reviews_ltm           19368 non-null  int64
 17  Pub_date                        19368 non-null  str
 18  Difference_date                 17674 non-null  float64
 19  month_name                      19368 non-null  str
 20  year                            19368 non-null  int64
dtypes: float64(7), int64(5), str(9)
memory usage: 3.1 MB

In [7]:
christ_clean.sample(10)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,Pub_date,Difference_date,month_name,year
10991,1168540827508543105,Haka House-Entire 8 Bed Dorm Ens,565751605.0,Haka House Hostel Christchurch,Christchurch City,Central Ward,-43.532190,172.629840,Private room,767.0,...,0,NaN,NaN,10.0,88,0,2026-04-16,NaN,April,2026
6298,22555308,Peaceful Pocket,12678171.0,Jo,Christchurch City,Innes Ward,-43.503570,172.638840,Entire home/apt,343.0,...,20,2026-02-20,1970-01-01 00:00:00.000000000,2.0,8,3,2026-03-17,25.0,March,2026
9523,22509016,Comfortable stay with comforting view,42103536.0,Tia,Christchurch City,Hornby Ward,-43.526730,172.527330,Entire home/apt,388.0,...,42,2026-04-15,1970-01-01 00:00:00.000000000,1.0,80,22,2026-04-16,1.0,April,2026
11147,1245418435115870909,Little house with big views!,125024152.0,Jacinta And Marc,Christchurch City,Banks Peninsula Ward,-43.601728,172.691516,Entire home/apt,252.0,...,122,2026-04-19,1970-01-01 00:00:00.000000006,1.0,233,80,2026-04-16,-3.0,April,2026
18546,1040165976858575249,Stylish~Central~Gated free car park-King Bed,537318846.0,Jemima,Christchurch City,Central Ward,-43.517060,172.635950,Entire home/apt,189.0,...,158,2026-06-06,1970-01-01 00:00:00.000000005,5.0,83,83,2026-06-19,13.0,June,2026
11781,1475637350905928884,Beautiful Views & Heated Pool,82363146.0,Wendy,Christchurch City,Cashmere Ward,-43.585160,172.635940,Entire home/apt,NaN,...,1,2026-01-01,1970-01-01 00:00:00.000000000,4.0,0,1,2026-04-16,105.0,April,2026
9027,1590709818991360574,Room near Hagley Park,61637206.0,Cathy,Christchurch City,Riccarton Ward,-43.534080,172.611840,Private room,90.0,...,17,2026-03-19,1970-01-01 00:00:00.000000011,2.0,78,17,2026-03-17,-2.0,March,2026
11455,1359042873049714360,"Available curtain room, pls book",679056810.0,Saravanan,Christchurch City,Hornby Ward,-43.535976,172.547984,Private room,86.0,...,1,2025-02-22,1970-01-01 00:00:00.000000000,1.0,365,0,2026-04-16,418.0,April,2026
7362,990020082081431864,Gorgeous Getaway on Gloucester St- 1 Bed 1 Bath,482671075.0,Care Property Stays,Christchurch City,Central Ward,-43.529572,172.644922,Entire home/apt,223.0,...,168,2026-02-24,1970-01-01 00:00:00.000000005,147.0,257,45,2026-03-17,21.0,March,2026
14789,875606252958991505,Luxury Merivale Villa,222941036.0,Brendan,Christchurch City,Papanui Ward,-43.504669,172.615136,Entire home/apt,374.0,...,86,2026-05-10,1970-01-01 00:00:00.000000002,1.0,4,22,2026-05-23,13.0,May,2026

In [8]:
coordinates = christ_clean[["latitude", "longitude"]].drop_duplicates()

print("Total rows:", len(christ_clean))
print("Unique latitude + longitude pairs:", len(coordinates))

Total rows: 19368
Unique latitude + longitude pairs: 3905

In [9]:
import requests

In [10]:


API_KEY = "bfb0cc9cc0784fa58767555d85581629"
LAYER_ID = "123515"


latitude = christ_clean.iloc[0]['latitude']
longitude = christ_clean.iloc[0]['longitude']

url = "https://koordinates.com/services/query/v1/vector.json"

params = {
    "key": API_KEY,
    "layer": LAYER_ID,
    "x": longitude,
    "y": latitude,
    "max_results": 1,
    "radius": 0,
    "with_field_names": "true"
}

response = requests.get(url, params=params)

print("Status code:", response.status_code)
print("URL:", response.url)
print("Response:")
print(response.text)

Status code: 403
URL: https://koordinates.com/services/query/v1/vector.json?key=bfb0cc9cc0784fa58767555d85581629&layer=123515&x=172.57088&y=-43.47002&max_results=1&radius=0&with_field_names=true
Response:
invalid-api-key: Provide a valid api key

In [11]:
data = response.json()

area_code = data["vectorQuery"]["layers"]["123515"]["features"][0]["properties"]["SA22026_V1_00"]

print(area_code)

KeyboardInterrupt

In [ ]:
print(
    christ_clean[["latitude", "longitude"]].duplicated().sum()
)

15463

In [ ]:
import requests
import pandas as pd
import time

API_KEY = "819797b85c5949fdb5a1dbc4cd468409"
LAYER_ID = 123515
URL = "https://koordinates.com/services/query/v1/vector.json"

# Get unique coordinates
coordinates = (
    christ_clean[["latitude", "longitude"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("Unique coordinates:", len(coordinates))

area_codes = []

start_time = time.time()

for i, row in coordinates.iterrows():

    latitude = row["latitude"]
    longitude = row["longitude"]

    params = {
        "key": API_KEY,
        "layer": LAYER_ID,
        "x": longitude,
        "y": latitude,
        "max_results": 1,
        "radius": 0,
        "with_field_names": "true"
    }

    try:
        response = requests.get(
            URL,
            params=params,
            timeout=30
        )

        if response.status_code == 200:

            data = response.json()

            features = (
                data["vectorQuery"]
                ["layers"][str(LAYER_ID)]
                ["features"]
            )

            if features:
                area_code = features[0]["properties"].get(
                    "SA22026_V1_00"
                )
            else:
                area_code = None

        else:
            print("Error:", response.status_code)
            area_code = None

    except Exception as e:
        print("Error:", e)
        area_code = None

    area_codes.append(area_code)

    # Show progress every 100 requests
    if (i + 1) % 100 == 0:
        elapsed = time.time() - start_time
        print(
            f"{i + 1} / {len(coordinates)} completed "
            f"({elapsed / 60:.1f} minutes)"
        )

print("Finished!")

coordinates["area_code"] = area_codes

Unique coordinates: 3905
100 / 3905 completed (0.5 minutes)
200 / 3905 completed (1.0 minutes)
300 / 3905 completed (1.5 minutes)
400 / 3905 completed (2.0 minutes)
500 / 3905 completed (2.5 minutes)
600 / 3905 completed (3.0 minutes)
700 / 3905 completed (3.5 minutes)
800 / 3905 completed (4.1 minutes)
900 / 3905 completed (4.5 minutes)
1000 / 3905 completed (5.0 minutes)
1100 / 3905 completed (5.5 minutes)
1200 / 3905 completed (6.0 minutes)
1300 / 3905 completed (6.4 minutes)
1400 / 3905 completed (6.9 minutes)
1500 / 3905 completed (7.3 minutes)
1600 / 3905 completed (7.9 minutes)
1700 / 3905 completed (8.4 minutes)
1800 / 3905 completed (8.9 minutes)
1900 / 3905 completed (9.4 minutes)
2000 / 3905 completed (9.9 minutes)
2100 / 3905 completed (10.4 minutes)
2200 / 3905 completed (10.8 minutes)
2300 / 3905 completed (11.3 minutes)
2400 / 3905 completed (11.7 minutes)
2500 / 3905 completed (12.2 minutes)
2600 / 3905 completed (12.6 minutes)
2700 / 3905 completed (13.1 minutes)
2800 / 3905 completed (13.6 minutes)
2900 / 3905 completed (14.0 minutes)
3000 / 3905 completed (14.5 minutes)
3100 / 3905 completed (15.2 minutes)
3200 / 3905 completed (15.7 minutes)
3300 / 3905 completed (16.3 minutes)
3400 / 3905 completed (16.8 minutes)
3500 / 3905 completed (17.3 minutes)
3600 / 3905 completed (17.8 minutes)
3700 / 3905 completed (18.3 minutes)
3800 / 3905 completed (18.8 minutes)
3900 / 3905 completed (19.4 minutes)
Finished!

In [ ]:
christ_clean = christ_clean.merge(
    coordinates,
    on=["latitude", "longitude"],
    how="left"
)

In [ ]:
print(christ_clean[["latitude", "longitude", "area_code"]].head(20))
print("Missing area codes:", christ_clean["area_code"].isna().sum())

     latitude   longitude area_code
0  -43.470020  172.570880    316700
1  -43.532700  172.664030    327902
2  -43.511490  172.625400    322200
3  -43.482864  172.668660    321302
4  -43.538437  172.578953    322700
5  -43.511080  172.623880    322200
6  -43.529020  172.610730    325200
7  -43.562280  172.712870    332000
8  -43.558840  172.553750    322900
9  -43.564680  172.710980    332000
10 -43.518340  172.649520    325302
11 -43.532820  172.627320    324900
12 -43.529570  172.643220    327000
13 -43.550027  172.639225    329400
14 -43.539760  172.664720    328900
15 -43.528600  172.569310    321800
16 -43.466460  172.584370    317000
17 -43.537838  172.638454    327100
18 -43.551550  172.605308    326900
19 -43.526425  172.639876    325800
Missing area codes: 0

In [ ]:
christ_clean.head(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,Pub_date,Difference_date,month_name,year,area_code
0,40183765,Ensuite Cabin (Sleeps 6),98758734.0,North South Holiday Park,Christchurch City,Harewood Ward,-43.470020,172.570880,Private room,NaN,...,NaN,NaN,20.0,317,0,2025-11-07,NaN,November,2025,316700
1,1149729199964166318,Handy city center. Simple room,298456605.0,Tony,Christchurch City,Central Ward,-43.532700,172.664030,Private room,NaN,...,2025-07-15,1970-01-01 00:00:00.000000001,6.0,0,21,2025-11-07,115.0,November,2025,327902
2,1097487,Heritage Magic in Merivale,4993285.0,Paulette,Christchurch City,Fendalton Ward,-43.511490,172.625400,Private room,166.0,...,2025-03-03,1970-01-01 00:00:00.000000002,1.0,221,14,2025-11-07,249.0,November,2025,322200
3,1339647508906377362,Settle into the sun set,54299306.0,Sarena,Christchurch City,Burwood Ward,-43.482864,172.668660,Entire home/apt,NaN,...,2025-04-26,1970-01-01 00:00:00.000000000,1.0,0,2,2025-11-07,195.0,November,2025,321302
4,1211070132323635531,Eco Spa-bath Studio,179297759.0,Peng,Christchurch City,Riccarton Ward,-43.538437,172.578953,Private room,126.0,...,2025-03-01,1970-01-01 00:00:00.000000000,20.0,359,5,2025-11-07,251.0,November,2025,322700

In [ ]:
christ_clean.to_csv(r'C:\Users\VISHAL\Desktop\g2\christ_area_codes.csv', index=False)

In [ ]:
christ_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 19368 entries, 0 to 19367
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              19368 non-null  int64
 1   name                            19368 non-null  str
 2   host_id                         19368 non-null  float64
 3   host_name                       19367 non-null  str
 4   neighbourhood_group             19368 non-null  str
 5   neighbourhood                   19368 non-null  str
 6   latitude                        19368 non-null  float64
 7   longitude                       19368 non-null  float64
 8   room_type                       19368 non-null  str
 9   price                           18128 non-null  float64
 10  minimum_nights                  19359 non-null  float64
 11  number_of_reviews               19368 non-null  int64
 12  last_review                     17674 non-null  str
 13  reviews_per_month               17674 non-null  str
 14  calculated_host_listings_count  19368 non-null  float64
 15  availability_365                19368 non-null  int64
 16  number_of_reviews_ltm           19368 non-null  int64
 17  Pub_date                        19368 non-null  str
 18  Difference_date                 17674 non-null  float64
 19  month_name                      19368 non-null  str
 20  year                            19368 non-null  int64
 21  area_code                       19368 non-null  str
dtypes: float64(7), int64(5), str(10)
memory usage: 3.3 MB

In [ ]:
print(christ_clean["area_code"].dtype)
print(df_tnc["Location Id"].dtype)

str
float64

In [ ]:
df_tnc["location id"] = (
    df_tnc["Location Id"]
    .astype("Int64")
    .astype("string")
)

In [ ]:
print(df_tnc["location id"].head())
print(df_tnc["location id"].dtype)

0    100100
1    100600
2    100700
3    100800
4    101100
Name: location id, dtype: string
string

In [ ]:
df_tnc = df_tnc.rename(columns={"Location Id": "area_code"})

In [ ]:
df_tnc.info()

<class 'pandas.DataFrame'>
RangeIndex: 26991 entries, 0 to 26990
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TimeFrame                26991 non-null  str
 1   area_code                26991 non-null  float64
 2   Dwelling Type            26991 non-null  str
 3   Number Of Beds           26133 non-null  str
 4   Total Bonds              26991 non-null  int64
 5   Active Bonds             26991 non-null  int64
 6   Closed Bonds             26991 non-null  int64
 7   Median Rent              26991 non-null  float64
 8   Geometric Mean Rent      26991 non-null  float64
 9   Upper Quartile Rent      26991 non-null  float64
 10  Lower Quartile Rent      26991 non-null  float64
 11  Log Std Dev Weekly Rent  26991 non-null  float64
 12  location id              26991 non-null  string
dtypes: float64(6), int64(3), str(3), string(1)
memory usage: 2.7 MB

In [ ]:
print(df_tnc["TimeFrame"].unique())

<StringArray>
['2026-04-01', '2026-01-01', '2025-10-01']
Length: 3, dtype: str

In [ ]:
print(df_tnc["TimeFrame"].dtype)

str

In [ ]:
print(christ_clean["Pub_date"].min())
print(christ_clean["Pub_date"].max())

print(christ_clean["last_review"].min())
print(christ_clean["last_review"].max())

2025-11-07
2026-06-19
2014-04-14
2026-06-21

In [12]:
df_tnc= pd.read_csv(r"C:\Users\VISHAL\Desktop\g2\cleaned_dataset_bond.csv")

In [13]:
christ_area= pd.read_csv(r"C:\Users\VISHAL\Desktop\g2\christ_area_codes.csv")

In [24]:
christ_area.info()

<class 'pandas.DataFrame'>
RangeIndex: 19368 entries, 0 to 19367
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              19368 non-null  int64
 1   name                            19368 non-null  str
 2   host_id                         19368 non-null  float64
 3   host_name                       19367 non-null  str
 4   neighbourhood_group             19368 non-null  str
 5   neighbourhood                   19368 non-null  str
 6   latitude                        19368 non-null  float64
 7   longitude                       19368 non-null  float64
 8   room_type                       19368 non-null  str
 9   price                           18128 non-null  float64
 10  minimum_nights                  19359 non-null  float64
 11  number_of_reviews               19368 non-null  int64
 12  last_review                     17674 non-null  str
 13  reviews_per_month               17674 non-null  str
 14  calculated_host_listings_count  19368 non-null  float64
 15  availability_365                19368 non-null  int64
 16  number_of_reviews_ltm           19368 non-null  int64
 17  Pub_date                        19368 non-null  str
 18  Difference_date                 17674 non-null  float64
 19  month_name                      19368 non-null  str
 20  year                            19368 non-null  int64
 21  area_code                       19368 non-null  Int64
dtypes: Int64(1), float64(7), int64(5), str(9)
memory usage: 3.3 MB

In [40]:
df_tnc['TimeFrame'] = pd.to_datetime(df_tnc['TimeFrame'])

In [41]:
df_tnc.info()

<class 'pandas.DataFrame'>
RangeIndex: 26991 entries, 0 to 26990
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TimeFrame                26991 non-null  datetime64[us]
 1   area_code                26991 non-null  Int64
 2   Dwelling Type            26991 non-null  str
 3   Number Of Beds           26133 non-null  str
 4   Total Bonds              26991 non-null  int64
 5   Active Bonds             26991 non-null  int64
 6   Closed Bonds             26991 non-null  int64
 7   Median Rent              26991 non-null  float64
 8   Geometric Mean Rent      26991 non-null  float64
 9   Upper Quartile Rent      26991 non-null  float64
 10  Lower Quartile Rent      26991 non-null  float64
 11  Log Std Dev Weekly Rent  26991 non-null  float64
dtypes: Int64(1), datetime64[us](1), float64(5), int64(3), str(2)
memory usage: 2.5 MB

In [16]:
df_tnc = df_tnc.rename(columns={"Location Id": "area_code"})

In [19]:
df_tnc["area_code"] = pd.to_numeric(
    df_tnc["area_code"], errors="coerce"
).astype("Int64")

In [23]:
christ_area["area_code"] = pd.to_numeric(
    christ_area["area_code"], errors="coerce"
).astype("Int64")

In [30]:
christ_area["Pub_date"] = pd.to_datetime(
    christ_area["Pub_date"]
)

christ_area["TimeFrame"] = (
    christ_area["Pub_date"]
    .dt.to_period("Q")
    .dt.start_time
)

In [31]:
christ_area.info()

<class 'pandas.DataFrame'>
RangeIndex: 19368 entries, 0 to 19367
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              19368 non-null  int64
 1   name                            19368 non-null  str
 2   host_id                         19368 non-null  float64
 3   host_name                       19367 non-null  str
 4   neighbourhood_group             19368 non-null  str
 5   neighbourhood                   19368 non-null  str
 6   latitude                        19368 non-null  float64
 7   longitude                       19368 non-null  float64
 8   room_type                       19368 non-null  str
 9   price                           18128 non-null  float64
 10  minimum_nights                  19359 non-null  float64
 11  number_of_reviews               19368 non-null  int64
 12  last_review                     17674 non-null  str
 13  reviews_per_month               17674 non-null  str
 14  calculated_host_listings_count  19368 non-null  float64
 15  availability_365                19368 non-null  int64
 16  number_of_reviews_ltm           19368 non-null  int64
 17  Pub_date                        19368 non-null  datetime64[us]
 18  Difference_date                 17674 non-null  float64
 19  month_name                      19368 non-null  str
 20  year                            19368 non-null  int64
 21  area_code                       19368 non-null  Int64
 22  TimeFrame                       19368 non-null  datetime64[us]
dtypes: Int64(1), datetime64[us](2), float64(7), int64(5), str(8)
memory usage: 3.4 MB

In [32]:
print(christ_area[["Pub_date", "TimeFrame", "area_code"]].head(20))

     Pub_date  TimeFrame  area_code
0  2025-11-07 2025-10-01     316700
1  2025-11-07 2025-10-01     327902
2  2025-11-07 2025-10-01     322200
3  2025-11-07 2025-10-01     321302
4  2025-11-07 2025-10-01     322700
5  2025-11-07 2025-10-01     322200
6  2025-11-07 2025-10-01     325200
7  2025-11-07 2025-10-01     332000
8  2025-11-07 2025-10-01     322900
9  2025-11-07 2025-10-01     332000
10 2025-11-07 2025-10-01     325302
11 2025-11-07 2025-10-01     324900
12 2025-11-07 2025-10-01     327000
13 2025-11-07 2025-10-01     329400
14 2025-11-07 2025-10-01     328900
15 2025-11-07 2025-10-01     321800
16 2025-11-07 2025-10-01     317000
17 2025-11-07 2025-10-01     327100
18 2025-11-07 2025-10-01     326900
19 2025-11-07 2025-10-01     325800

In [33]:
duplicate_keys = df_tnc.duplicated(
    subset=["area_code", "TimeFrame"]
).sum()

print("Duplicate area_code + TimeFrame combinations:", duplicate_keys)

Duplicate area_code + TimeFrame combinations: 22060

In [34]:
print(
    df_tnc.groupby(
        ["area_code", "TimeFrame"]
    ).size().value_counts().sort_index()
)

1      159
2      732
3      216
4     1248
5      299
6      894
7      303
8      435
9      176
10     184
11      84
12      66
13      34
14      29
15      24
16       9
17      10
18       9
19       4
20       2
21       7
22       2
23       1
25       1
26       1
30       1
33       1
Name: count, dtype: int64

In [42]:
matching_keys = christ_area.merge(
    df_tnc[["area_code", "TimeFrame"]].drop_duplicates(),
    on=["area_code", "TimeFrame"],
    how="inner"
)

In [43]:
print("Airbnb rows with a matching Bond area + time:")
print(len(matching_keys))

Airbnb rows with a matching Bond area + time:
14767

In [47]:
print(
    df_tnc.duplicated(
        ["area_code", "TimeFrame"]
    ).sum()
)

22060

In [48]:
print(
    df_tnc.groupby(
        ["area_code", "TimeFrame"]
    ).size().describe()
)

count    4931.000000
mean        5.473738
std         3.087150
min         1.000000
25%         4.000000
50%         5.000000
75%         7.000000
max        33.000000
dtype: float64

In [49]:
print("Dwelling Types:")
print(df_tnc["Dwelling Type"].unique())

print("\nNumber of Beds:")
print(df_tnc["Number Of Beds"].unique())

Dwelling Types:
<StringArray>
['ALL', 'Apartment', 'Boarding House', 'Flat', 'House', 'Room']
Length: 6, dtype: str

Number of Beds:
<StringArray>
['1', '2', '3', '4', '5', '9', 'ALL', '5+', nan, '6']
Length: 10, dtype: str

In [50]:
print(
    df_tnc[
        (df_tnc["Dwelling Type"] == "ALL") &
        (df_tnc["Number Of Beds"] == "ALL")
    ].shape
)

(4865, 12)

In [51]:
df_tnc_all = df_tnc[
    (df_tnc["Dwelling Type"] == "ALL") &
    (df_tnc["Number Of Beds"] == "ALL")
].copy()

In [52]:
print("Rows in original Bond data:", len(df_tnc))
print("Rows in ALL/ALL Bond data:", len(df_tnc_all))

Rows in original Bond data: 26991
Rows in ALL/ALL Bond data: 4865

In [53]:
duplicate_keys = df_tnc_all.duplicated(
    ["area_code", "TimeFrame"]
).sum()

print("Duplicate area_code + TimeFrame:", duplicate_keys)

Duplicate area_code + TimeFrame: 0

In [55]:
merged_data = christ_area.merge(
    df_tnc_all,
    on=["area_code", "TimeFrame"],
    how="left",
    validate="many_to_one"
)

In [164]:
df_tnc_all.info()

<class 'pandas.DataFrame'>
Index: 4865 entries, 2446 to 21683
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TimeFrame                4865 non-null   datetime64[us]
 1   area_code                4865 non-null   Int64
 2   Dwelling Type            4865 non-null   str
 3   Number Of Beds           4865 non-null   str
 4   Total Bonds              4865 non-null   int64
 5   Active Bonds             4865 non-null   int64
 6   Closed Bonds             4865 non-null   int64
 7   Median Rent              4865 non-null   float64
 8   Geometric Mean Rent      4865 non-null   float64
 9   Upper Quartile Rent      4865 non-null   float64
 10  Lower Quartile Rent      4865 non-null   float64
 11  Log Std Dev Weekly Rent  4865 non-null   float64
dtypes: Int64(1), datetime64[us](1), float64(5), int64(3), str(2)
memory usage: 498.9 KB

In [56]:
print("Before merge:", len(christ_clean))
print("After merge:", len(merged_data))

Before merge: 19368
After merge: 19368

In [57]:
print(
    "Airbnb rows with Bond data:",
    merged_data["Median Rent"].notna().sum()
)

print(
    "Airbnb rows without Bond data:",
    merged_data["Median Rent"].isna().sum()
)

Airbnb rows with Bond data: 14722
Airbnb rows without Bond data: 4646

In [79]:
print(
    df_tnc_all.duplicated(
        ["area_code", "TimeFrame"]
    ).sum()
)

0

In [162]:
print(
    merged_data[
        [
            "area_code",
            "TimeFrame",
            "price",
            "Median Rent",
            "Total Bonds",
            "Active Bonds"
        ]
    ].sample(20)
)

       area_code  TimeFrame  price  Median Rent  Total Bonds  Active Bonds
15945     321101 2026-04-01  514.0          NaN          NaN           NaN
6850      332901 2026-01-01  129.0          NaN          NaN           NaN
5545      325800 2025-10-01  132.0        495.0         99.0        1128.0
18909     325700 2026-04-01  228.0        535.0         54.0         441.0
114       332000 2025-10-01  175.0        710.0         24.0         153.0
15577     327000 2026-04-01  251.0        500.0        141.0         987.0
11392     327100 2026-04-01  161.0        520.0         42.0         276.0
2689      325700 2025-10-01  246.0        550.0         54.0         453.0
12277     322700 2026-04-01  355.0        518.0         24.0         528.0
3750      332501 2025-10-01  270.0          NaN          NaN           NaN
14951     327200 2026-04-01  164.0        560.0         21.0         288.0
9647      327200 2026-04-01  240.0        560.0         21.0         288.0
363       328700 2025-10-01  112.0        533.0         30.0         351.0
1602      326600 2025-10-01  177.0        508.0          6.0          33.0
15130     329500 2026-04-01  126.0        650.0          9.0         138.0
1833      333300 2025-10-01  195.0          NaN          NaN           NaN
4593      326100 2025-10-01  251.0        455.0         72.0         846.0
16875     325800 2026-04-01  171.0        499.0        105.0        1131.0
17295     333201 2026-04-01  628.0          NaN          NaN           NaN
11518     333500 2026-04-01  368.0          NaN          NaN           NaN

In [170]:
merged_data.to_csv(r"C:\Users\VISHAL\Desktop\g2\christ_bond_merged.csv", index=False)