In [5]:
import pandas as pd

In [72]:
df_tnc= pd.read_csv(r"C:\Users\VISHAL\Desktop\g2\cleaned_dataset_bond.csv")

In [7]:
df_tnc.sample(5)

,TimeFrame,Location Id,Dwelling Type,Number Of Beds,Total Bonds,Active Bonds,Closed Bonds,Median Rent,Geometric Mean Rent,Upper Quartile Rent,Lower Quartile Rent,Log Std Dev Weekly Rent
2682,2026-04-01,131400.0,ALL,ALL,6,108,9,960.0,959.0,1263.0,808.0,0.3547
22216,2025-10-01,120200.0,Apartment,2,15,72,3,625.0,648.0,660.0,600.0,0.1184
3002,2026-04-01,165100.0,ALL,ALL,9,129,9,775.0,875.0,1101.0,735.0,0.4339
4854,2026-04-01,140100.0,House,1,6,15,3,1215.0,1099.0,1623.0,793.0,0.4973
4137,2026-04-01,348400.0,Apartment,1,12,84,3,510.0,455.0,550.0,483.0,0.4442

In [8]:
df_tnc.info()

<class 'pandas.DataFrame'>
RangeIndex: 26991 entries, 0 to 26990
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TimeFrame                26991 non-null  str
 1   Location Id              26991 non-null  float64
 2   Dwelling Type            26991 non-null  str
 3   Number Of Beds           26133 non-null  str
 4   Total Bonds              26991 non-null  int64
 5   Active Bonds             26991 non-null  int64
 6   Closed Bonds             26991 non-null  int64
 7   Median Rent              26991 non-null  float64
 8   Geometric Mean Rent      26991 non-null  float64
 9   Upper Quartile Rent      26991 non-null  float64
 10  Lower Quartile Rent      26991 non-null  float64
 11  Log Std Dev Weekly Rent  26991 non-null  float64
dtypes: float64(6), int64(3), str(3)
memory usage: 2.5 MB

In [9]:
christ_clean= pd.read_csv(r"C:\Users\VISHAL\Desktop\g2\christ_new_filt.csv")

In [10]:
christ_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 19368 entries, 0 to 19367
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              19368 non-null  int64
 1   name                            19368 non-null  str
 2   host_id                         19368 non-null  float64
 3   host_name                       19367 non-null  str
 4   neighbourhood_group             19368 non-null  str
 5   neighbourhood                   19368 non-null  str
 6   latitude                        19368 non-null  float64
 7   longitude                       19368 non-null  float64
 8   room_type                       19368 non-null  str
 9   price                           18128 non-null  float64
 10  minimum_nights                  19359 non-null  float64
 11  number_of_reviews               19368 non-null  int64
 12  last_review                     17674 non-null  str
 13  reviews_per_month               17674 non-null  str
 14  calculated_host_listings_count  19368 non-null  float64
 15  availability_365                19368 non-null  int64
 16  number_of_reviews_ltm           19368 non-null  int64
 17  Pub_date                        19368 non-null  str
 18  Difference_date                 17674 non-null  float64
 19  month_name                      19368 non-null  str
 20  year                            19368 non-null  int64
dtypes: float64(7), int64(5), str(9)
memory usage: 3.1 MB

In [11]:
christ_clean.sample(10)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,Pub_date,Difference_date,month_name,year
13636,1691064438716213479,Brand New One Bedroom Retreat on Moorhouse,331763232.0,Managed By Williams,Christchurch City,Central Ward,-43.538530,172.633740,Entire home/apt,191.0,...,0,NaN,NaN,153.0,351,0,2026-05-23,NaN,May,2026
2436,1290860787845700041,Whare iti on Johns.,82159480.0,Rebecca,Christchurch City,Harewood Ward,-43.461351,172.586720,Entire home/apt,153.0,...,38,2025-09-06,1970-01-01 00:00:00.000000004,1.0,31,38,2025-11-07,62.0,November,2025
14401,1573093537414160276,"Private En-suite, Sunny 2nd Floor, Near Westfield",697785165.0,Lin,Christchurch City,Riccarton Ward,-43.533231,172.592978,Private room,113.0,...,12,2026-04-25,1970-01-01 00:00:00.000000003,2.0,180,12,2026-05-23,28.0,May,2026
5121,645862508946385530,Central City Loft - Sleeps 10,202585247.0,Ohana,Christchurch City,Central Ward,-43.533150,172.638110,Entire home/apt,450.0,...,312,2025-07-27,1970-01-01 00:00:00.000000007,123.0,0,54,2025-11-07,103.0,November,2025
14623,1084148394653577698,"Near, but feels far",174666921.0,Rebecca,Christchurch City,Banks Peninsula Ward,-43.627420,172.741700,Entire home/apt,161.0,...,16,2026-04-11,1970-01-01 00:00:00.000000000,1.0,260,6,2026-05-23,42.0,May,2026
9970,47803376,Classic Triple Room,270614463.0,Samuel William,Christchurch City,Central Ward,-43.531550,172.628620,Private room,275.0,...,87,2026-01-02,1970-01-01 00:00:00.000000001,14.0,339,18,2026-04-16,104.0,April,2026
5975,34062192,Cashmere apartment with amazing views.,257214205.0,Barry,Christchurch City,Cashmere Ward,-43.579710,172.637700,Entire home/apt,84.0,...,260,2025-11-01,1970-01-01 00:00:00.000000003,2.0,163,36,2025-11-07,6.0,November,2025
18042,20159264,Hawthornden Studio - Rural Retreat In ChCh City,143455926.0,Sarah,Christchurch City,Waimairi Ward,-43.502110,172.553570,Entire home/apt,177.0,...,845,2026-06-14,1970-01-01 00:00:00.000000007,1.0,151,84,2026-06-19,5.0,June,2026
18119,1681511506750219292,Azure Soar - UC&Riccarton - Private Bathroom R...,477454854.0,Denny,Christchurch City,Riccarton Ward,-43.536240,172.590300,Private room,89.0,...,0,NaN,NaN,5.0,62,0,2026-06-19,NaN,June,2026
18159,1350171874683360737,Book a room in home - Tranquil Oasis close to ...,164752883.0,Prachi,Christchurch City,Riccarton Ward,-43.534993,172.585277,Private room,78.0,...,0,NaN,NaN,1.0,363,0,2026-06-19,NaN,June,2026

In [12]:
coordinates = christ_clean[["latitude", "longitude"]].drop_duplicates()

print("Total rows:", len(christ_clean))
print("Unique latitude + longitude pairs:", len(coordinates))

Total rows: 19368
Unique latitude + longitude pairs: 3905

In [13]:
import requests

In [14]:


API_KEY = "bfb0cc9cc0784fa58767555d85581629"
LAYER_ID = "123515"


latitude = christ_clean.iloc[0]['latitude']
longitude = christ_clean.iloc[0]['longitude']

url = "https://koordinates.com/services/query/v1/vector.json"

params = {
    "key": API_KEY,
    "layer": LAYER_ID,
    "x": longitude,
    "y": latitude,
    "max_results": 1,
    "radius": 0,
    "with_field_names": "true"
}

response = requests.get(url, params=params)

print("Status code:", response.status_code)
print("URL:", response.url)
print("Response:")
print(response.text)

Status code: 403
URL: https://koordinates.com/services/query/v1/vector.json?key=bfb0cc9cc0784fa58767555d85581629&layer=123515&x=172.57088&y=-43.47002&max_results=1&radius=0&with_field_names=true
Response:
invalid-api-key: Provide a valid api key

In [15]:
data = response.json()

area_code = data["vectorQuery"]["layers"]["123515"]["features"][0]["properties"]["SA22026_V1_00"]

print(area_code)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [ ]:
print(
    christ_clean[["latitude", "longitude"]].duplicated().sum()
)

15463

In [ ]:
import requests
import pandas as pd
import time

API_KEY = "819797b85c5949fdb5a1dbc4cd468409"
LAYER_ID = 123515
URL = "https://koordinates.com/services/query/v1/vector.json"

# Get unique coordinates
coordinates = (
    christ_clean[["latitude", "longitude"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("Unique coordinates:", len(coordinates))

area_codes = []

start_time = time.time()

for i, row in coordinates.iterrows():

    latitude = row["latitude"]
    longitude = row["longitude"]

    params = {
        "key": API_KEY,
        "layer": LAYER_ID,
        "x": longitude,
        "y": latitude,
        "max_results": 1,
        "radius": 0,
        "with_field_names": "true"
    }

    try:
        response = requests.get(
            URL,
            params=params,
            timeout=30
        )

        if response.status_code == 200:

            data = response.json()

            features = (
                data["vectorQuery"]
                ["layers"][str(LAYER_ID)]
                ["features"]
            )

            if features:
                area_code = features[0]["properties"].get(
                    "SA22026_V1_00"
                )
            else:
                area_code = None

        else:
            print("Error:", response.status_code)
            area_code = None

    except Exception as e:
        print("Error:", e)
        area_code = None

    area_codes.append(area_code)

    # Show progress every 100 requests
    if (i + 1) % 100 == 0:
        elapsed = time.time() - start_time
        print(
            f"{i + 1} / {len(coordinates)} completed "
            f"({elapsed / 60:.1f} minutes)"
        )

print("Finished!")

coordinates["area_code"] = area_codes

Unique coordinates: 3905
100 / 3905 completed (0.5 minutes)
200 / 3905 completed (1.0 minutes)
300 / 3905 completed (1.5 minutes)
400 / 3905 completed (2.0 minutes)
500 / 3905 completed (2.5 minutes)
600 / 3905 completed (3.0 minutes)
700 / 3905 completed (3.5 minutes)
800 / 3905 completed (4.1 minutes)
900 / 3905 completed (4.5 minutes)
1000 / 3905 completed (5.0 minutes)
1100 / 3905 completed (5.5 minutes)
1200 / 3905 completed (6.0 minutes)
1300 / 3905 completed (6.4 minutes)
1400 / 3905 completed (6.9 minutes)
1500 / 3905 completed (7.3 minutes)
1600 / 3905 completed (7.9 minutes)
1700 / 3905 completed (8.4 minutes)
1800 / 3905 completed (8.9 minutes)
1900 / 3905 completed (9.4 minutes)
2000 / 3905 completed (9.9 minutes)
2100 / 3905 completed (10.4 minutes)
2200 / 3905 completed (10.8 minutes)
2300 / 3905 completed (11.3 minutes)
2400 / 3905 completed (11.7 minutes)
2500 / 3905 completed (12.2 minutes)
2600 / 3905 completed (12.6 minutes)
2700 / 3905 completed (13.1 minutes)
2800 / 3905 completed (13.6 minutes)
2900 / 3905 completed (14.0 minutes)
3000 / 3905 completed (14.5 minutes)
3100 / 3905 completed (15.2 minutes)
3200 / 3905 completed (15.7 minutes)
3300 / 3905 completed (16.3 minutes)
3400 / 3905 completed (16.8 minutes)
3500 / 3905 completed (17.3 minutes)
3600 / 3905 completed (17.8 minutes)
3700 / 3905 completed (18.3 minutes)
3800 / 3905 completed (18.8 minutes)
3900 / 3905 completed (19.4 minutes)
Finished!

In [ ]:
print(christ_clean[["latitude", "longitude", "area_code"]].head(20))
print("Missing area codes:", christ_clean["area_code"].isna().sum())

In [ ]:
christ_clean.head(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,Pub_date,Difference_date,month_name,year,area_code
0,40183765,Ensuite Cabin (Sleeps 6),98758734.0,North South Holiday Park,Christchurch City,Harewood Ward,-43.470020,172.570880,Private room,NaN,...,NaN,NaN,20.0,317,0,2025-11-07,NaN,November,2025,316700
1,1149729199964166318,Handy city center. Simple room,298456605.0,Tony,Christchurch City,Central Ward,-43.532700,172.664030,Private room,NaN,...,2025-07-15,1970-01-01 00:00:00.000000001,6.0,0,21,2025-11-07,115.0,November,2025,327902
2,1097487,Heritage Magic in Merivale,4993285.0,Paulette,Christchurch City,Fendalton Ward,-43.511490,172.625400,Private room,166.0,...,2025-03-03,1970-01-01 00:00:00.000000002,1.0,221,14,2025-11-07,249.0,November,2025,322200
3,1339647508906377362,Settle into the sun set,54299306.0,Sarena,Christchurch City,Burwood Ward,-43.482864,172.668660,Entire home/apt,NaN,...,2025-04-26,1970-01-01 00:00:00.000000000,1.0,0,2,2025-11-07,195.0,November,2025,321302
4,1211070132323635531,Eco Spa-bath Studio,179297759.0,Peng,Christchurch City,Riccarton Ward,-43.538437,172.578953,Private room,126.0,...,2025-03-01,1970-01-01 00:00:00.000000000,20.0,359,5,2025-11-07,251.0,November,2025,322700

In [18]:
christ_clean.to_csv(r'C:\Users\VISHAL\Desktop\g2\christ_area_codes.csv', index=False)

In [19]:
christ_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 19368 entries, 0 to 19367
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              19368 non-null  int64
 1   name                            19368 non-null  str
 2   host_id                         19368 non-null  float64
 3   host_name                       19367 non-null  str
 4   neighbourhood_group             19368 non-null  str
 5   neighbourhood                   19368 non-null  str
 6   latitude                        19368 non-null  float64
 7   longitude                       19368 non-null  float64
 8   room_type                       19368 non-null  str
 9   price                           18128 non-null  float64
 10  minimum_nights                  19359 non-null  float64
 11  number_of_reviews               19368 non-null  int64
 12  last_review                     17674 non-null  str
 13  reviews_per_month               17674 non-null  str
 14  calculated_host_listings_count  19368 non-null  float64
 15  availability_365                19368 non-null  int64
 16  number_of_reviews_ltm           19368 non-null  int64
 17  Pub_date                        19368 non-null  str
 18  Difference_date                 17674 non-null  float64
 19  month_name                      19368 non-null  str
 20  year                            19368 non-null  int64
dtypes: float64(7), int64(5), str(9)
memory usage: 3.1 MB

In [69]:
christ_area= pd.read_csv(r"C:\Users\VISHAL\Desktop\g2\christ_area_codes.csv")

In [71]:
christ_area.head(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,Pub_date,Difference_date,month_name,year,area_code
0,40183765,Ensuite Cabin (Sleeps 6),98758734.0,North South Holiday Park,Christchurch City,Harewood Ward,-43.470020,172.570880,Private room,NaN,...,NaN,NaN,20.0,317,0,2025-11-07,NaN,November,2025,316700
1,1149729199964166318,Handy city center. Simple room,298456605.0,Tony,Christchurch City,Central Ward,-43.532700,172.664030,Private room,NaN,...,2025-07-15,1970-01-01 00:00:00.000000001,6.0,0,21,2025-11-07,115.0,November,2025,327902
2,1097487,Heritage Magic in Merivale,4993285.0,Paulette,Christchurch City,Fendalton Ward,-43.511490,172.625400,Private room,166.0,...,2025-03-03,1970-01-01 00:00:00.000000002,1.0,221,14,2025-11-07,249.0,November,2025,322200
3,1339647508906377362,Settle into the sun set,54299306.0,Sarena,Christchurch City,Burwood Ward,-43.482864,172.668660,Entire home/apt,NaN,...,2025-04-26,1970-01-01 00:00:00.000000000,1.0,0,2,2025-11-07,195.0,November,2025,321302
4,1211070132323635531,Eco Spa-bath Studio,179297759.0,Peng,Christchurch City,Riccarton Ward,-43.538437,172.578953,Private room,126.0,...,2025-03-01,1970-01-01 00:00:00.000000000,20.0,359,5,2025-11-07,251.0,November,2025,322700

In [ ]:
print(christ_clean["area_code"].dtype)
print(df_tnc["Location Id"].dtype)

In [75]:
df_tnc["location id"] = (
    df_tnc["Location Id"]
    .astype("Int64")
    .astype("string")
)

In [76]:
print(df_tnc["location id"].head())
print(df_tnc["location id"].dtype)

0    100100
1    100600
2    100700
3    100800
4    101100
Name: location id, dtype: string
string

In [21]:
df_tnc = df_tnc.rename(columns={"Location Id": "area_code"})

In [22]:
df_tnc.info()

<class 'pandas.DataFrame'>
RangeIndex: 26991 entries, 0 to 26990
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TimeFrame                26991 non-null  str
 1   area_code                26991 non-null  float64
 2   Dwelling Type            26991 non-null  str
 3   Number Of Beds           26133 non-null  str
 4   Total Bonds              26991 non-null  int64
 5   Active Bonds             26991 non-null  int64
 6   Closed Bonds             26991 non-null  int64
 7   Median Rent              26991 non-null  float64
 8   Geometric Mean Rent      26991 non-null  float64
 9   Upper Quartile Rent      26991 non-null  float64
 10  Lower Quartile Rent      26991 non-null  float64
 11  Log Std Dev Weekly Rent  26991 non-null  float64
dtypes: float64(6), int64(3), str(3)
memory usage: 2.5 MB

In [77]:
print(df_tnc["TimeFrame"].unique())

<StringArray>
['2026-04-01', '2026-01-01', '2025-10-01']
Length: 3, dtype: str

In [24]:
print(df_tnc["TimeFrame"].dtype)

str

In [25]:
print(christ_clean["Pub_date"].min())
print(christ_clean["Pub_date"].max())

print(christ_clean["last_review"].min())
print(christ_clean["last_review"].max())

2025-11-07
2026-06-19
2014-04-14
2026-06-21

In [26]:
df_tnc= pd.read_csv(r"C:\Users\VISHAL\Desktop\g2\cleaned_dataset_bond.csv")

In [27]:
christ_area= pd.read_csv(r"C:\Users\VISHAL\Desktop\g2\christ_area_codes.csv")

In [78]:
christ_area.info()

<class 'pandas.DataFrame'>
RangeIndex: 19368 entries, 0 to 19367
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              19368 non-null  int64
 1   name                            19368 non-null  str
 2   host_id                         19368 non-null  float64
 3   host_name                       19367 non-null  str
 4   neighbourhood_group             19368 non-null  str
 5   neighbourhood                   19368 non-null  str
 6   latitude                        19368 non-null  float64
 7   longitude                       19368 non-null  float64
 8   room_type                       19368 non-null  str
 9   price                           18128 non-null  float64
 10  minimum_nights                  19359 non-null  float64
 11  number_of_reviews               19368 non-null  int64
 12  last_review                     17674 non-null  str
 13  reviews_per_month               17674 non-null  str
 14  calculated_host_listings_count  19368 non-null  float64
 15  availability_365                19368 non-null  int64
 16  number_of_reviews_ltm           19368 non-null  int64
 17  Pub_date                        19368 non-null  str
 18  Difference_date                 17674 non-null  float64
 19  month_name                      19368 non-null  str
 20  year                            19368 non-null  int64
 21  area_code                       19368 non-null  int64
dtypes: float64(7), int64(6), str(9)
memory usage: 3.3 MB

In [79]:
df_tnc['TimeFrame'] = pd.to_datetime(df_tnc['TimeFrame'])

In [80]:
df_tnc.info()

<class 'pandas.DataFrame'>
RangeIndex: 26991 entries, 0 to 26990
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TimeFrame                26991 non-null  datetime64[us]
 1   Location Id              26991 non-null  float64
 2   Dwelling Type            26991 non-null  str
 3   Number Of Beds           26133 non-null  str
 4   Total Bonds              26991 non-null  int64
 5   Active Bonds             26991 non-null  int64
 6   Closed Bonds             26991 non-null  int64
 7   Median Rent              26991 non-null  float64
 8   Geometric Mean Rent      26991 non-null  float64
 9   Upper Quartile Rent      26991 non-null  float64
 10  Lower Quartile Rent      26991 non-null  float64
 11  Log Std Dev Weekly Rent  26991 non-null  float64
 12  location id              26991 non-null  string
dtypes: datetime64[us](1), float64(6), int64(3), str(2), string(1)
memory usage: 2.7 MB

In [82]:
df_tnc = df_tnc.rename(columns={"Location Id": "area_code"})

In [83]:
df_tnc["area_code"] = pd.to_numeric(
    df_tnc["area_code"], errors="coerce"
).astype("Int64")

In [84]:
christ_area["area_code"] = pd.to_numeric(
    christ_area["area_code"], errors="coerce"
).astype("Int64")

In [85]:
christ_area["Pub_date"] = pd.to_datetime(
    christ_area["Pub_date"]
)

christ_area["TimeFrame"] = (
    christ_area["Pub_date"]
    .dt.to_period("Q")
    .dt.start_time
)

In [86]:
christ_area.info()

<class 'pandas.DataFrame'>
RangeIndex: 19368 entries, 0 to 19367
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              19368 non-null  int64
 1   name                            19368 non-null  str
 2   host_id                         19368 non-null  float64
 3   host_name                       19367 non-null  str
 4   neighbourhood_group             19368 non-null  str
 5   neighbourhood                   19368 non-null  str
 6   latitude                        19368 non-null  float64
 7   longitude                       19368 non-null  float64
 8   room_type                       19368 non-null  str
 9   price                           18128 non-null  float64
 10  minimum_nights                  19359 non-null  float64
 11  number_of_reviews               19368 non-null  int64
 12  last_review                     17674 non-null  str
 13  reviews_per_month               17674 non-null  str
 14  calculated_host_listings_count  19368 non-null  float64
 15  availability_365                19368 non-null  int64
 16  number_of_reviews_ltm           19368 non-null  int64
 17  Pub_date                        19368 non-null  datetime64[us]
 18  Difference_date                 17674 non-null  float64
 19  month_name                      19368 non-null  str
 20  year                            19368 non-null  int64
 21  area_code                       19368 non-null  Int64
 22  TimeFrame                       19368 non-null  datetime64[us]
dtypes: Int64(1), datetime64[us](2), float64(7), int64(5), str(8)
memory usage: 3.4 MB

In [87]:
print(christ_area[["Pub_date", "TimeFrame", "area_code"]].head(20))

     Pub_date  TimeFrame  area_code
0  2025-11-07 2025-10-01     316700
1  2025-11-07 2025-10-01     327902
2  2025-11-07 2025-10-01     322200
3  2025-11-07 2025-10-01     321302
4  2025-11-07 2025-10-01     322700
5  2025-11-07 2025-10-01     322200
6  2025-11-07 2025-10-01     325200
7  2025-11-07 2025-10-01     332000
8  2025-11-07 2025-10-01     322900
9  2025-11-07 2025-10-01     332000
10 2025-11-07 2025-10-01     325302
11 2025-11-07 2025-10-01     324900
12 2025-11-07 2025-10-01     327000
13 2025-11-07 2025-10-01     329400
14 2025-11-07 2025-10-01     328900
15 2025-11-07 2025-10-01     321800
16 2025-11-07 2025-10-01     317000
17 2025-11-07 2025-10-01     327100
18 2025-11-07 2025-10-01     326900
19 2025-11-07 2025-10-01     325800

In [36]:
duplicate_keys = df_tnc.duplicated(
    subset=["area_code", "TimeFrame"]
).sum()

print("Duplicate area_code + TimeFrame combinations:", duplicate_keys)

Duplicate area_code + TimeFrame combinations: 22060

In [37]:
print(
    df_tnc.groupby(
        ["area_code", "TimeFrame"]
    ).size().value_counts().sort_index()
)

1      159
2      732
3      216
4     1248
5      299
6      894
7      303
8      435
9      176
10     184
11      84
12      66
13      34
14      29
15      24
16       9
17      10
18       9
19       4
20       2
21       7
22       2
23       1
25       1
26       1
30       1
33       1
Name: count, dtype: int64

In [38]:
matching_keys = christ_area.merge(
    df_tnc[["area_code", "TimeFrame"]].drop_duplicates(),
    on=["area_code", "TimeFrame"],
    how="inner"
)

KeyError: 'area_code'

In [ ]:
print("Airbnb rows with a matching Bond area + time:")
print(len(matching_keys))

Airbnb rows with a matching Bond area + time:
14767

In [ ]:
print(
    df_tnc.duplicated(
        ["area_code", "TimeFrame"]
    ).sum()
)

22060

In [39]:
print(
    df_tnc.groupby(
        ["area_code", "TimeFrame"]
    ).size().describe()
)

count    4931.000000
mean        5.473738
std         3.087150
min         1.000000
25%         4.000000
50%         5.000000
75%         7.000000
max        33.000000
dtype: float64

In [40]:
print("Dwelling Types:")
print(df_tnc["Dwelling Type"].unique())

print("\nNumber of Beds:")
print(df_tnc["Number Of Beds"].unique())

Dwelling Types:
<StringArray>
['ALL', 'Apartment', 'Boarding House', 'Flat', 'House', 'Room']
Length: 6, dtype: str

Number of Beds:
<StringArray>
['1', '2', '3', '4', '5', '9', 'ALL', '5+', nan, '6']
Length: 10, dtype: str

In [41]:
print(
    df_tnc[
        (df_tnc["Dwelling Type"] == "ALL") &
        (df_tnc["Number Of Beds"] == "ALL")
    ].shape
)

(4865, 12)

In [42]:
df_tnc_all = df_tnc[
    (df_tnc["Dwelling Type"] == "ALL") &
    (df_tnc["Number Of Beds"] == "ALL")
].copy()

In [43]:
print("Rows in original Bond data:", len(df_tnc))
print("Rows in ALL/ALL Bond data:", len(df_tnc_all))

Rows in original Bond data: 26991
Rows in ALL/ALL Bond data: 4865

In [44]:
duplicate_keys = df_tnc_all.duplicated(
    ["area_code", "TimeFrame"]
).sum()

print("Duplicate area_code + TimeFrame:", duplicate_keys)

Duplicate area_code + TimeFrame: 0

In [ ]:
merged_data = christ_area.merge(
    df_tnc_all,
    on=["area_code", "TimeFrame"],
    how="left",
    validate="many_to_one"
)

In [ ]:
df_tnc_all.info()

<class 'pandas.DataFrame'>
Index: 4865 entries, 2446 to 21683
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TimeFrame                4865 non-null   datetime64[us]
 1   area_code                4865 non-null   Int64
 2   Dwelling Type            4865 non-null   str
 3   Number Of Beds           4865 non-null   str
 4   Total Bonds              4865 non-null   int64
 5   Active Bonds             4865 non-null   int64
 6   Closed Bonds             4865 non-null   int64
 7   Median Rent              4865 non-null   float64
 8   Geometric Mean Rent      4865 non-null   float64
 9   Upper Quartile Rent      4865 non-null   float64
 10  Lower Quartile Rent      4865 non-null   float64
 11  Log Std Dev Weekly Rent  4865 non-null   float64
dtypes: Int64(1), datetime64[us](1), float64(5), int64(3), str(2)
memory usage: 498.9 KB

In [ ]:
print("Before merge:", len(christ_clean))
print("After merge:", len(merged_data))

In [47]:
print(
    "Airbnb rows with Bond data:",
    merged_data["Median Rent"].notna().sum()
)

print(
    "Airbnb rows without Bond data:",
    merged_data["Median Rent"].isna().sum()
)

NameError: name 'merged_data' is not defined

In [48]:
print(
    df_tnc_all.duplicated(
        ["area_code", "TimeFrame"]
    ).sum()
)

0

In [ ]:
print(
    merged_data[
        [
            "area_code",
            "TimeFrame",
            "price",
            "Median Rent",
            "Total Bonds",
            "Active Bonds"
        ]
    ].sample(20)
)

In [96]:
merged_data.head(5)

NameError: name 'merged_data' is not defined

In [ ]:
merged_data.to_csv(r"C:\Users\VISHAL\Desktop\g2\christ_bond_merged.csv", index=False)

In [52]:
import sqlite3

In [53]:
conn = sqlite3.connect("my_database.sqlite")

In [ ]:
christ_area= pd.read_csv(r"C:\Users\VISHAL\Desktop\g2\christ_area_codes.csv")

In [88]:
dataset1 = christ_area.copy()
dataset2 = df_tnc_all.copy()

In [89]:
dataset1.to_sql("dataset1", conn, if_exists="replace", index=False)
dataset2.to_sql("dataset2", conn, if_exists="replace", index=False)

4865

In [90]:
christ_area.head(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,Pub_date,Difference_date,month_name,year,area_code,TimeFrame
0,40183765,Ensuite Cabin (Sleeps 6),98758734.0,North South Holiday Park,Christchurch City,Harewood Ward,-43.470020,172.570880,Private room,NaN,...,NaN,20.0,317,0,2025-11-07,NaN,November,2025,316700,2025-10-01
1,1149729199964166318,Handy city center. Simple room,298456605.0,Tony,Christchurch City,Central Ward,-43.532700,172.664030,Private room,NaN,...,1970-01-01 00:00:00.000000001,6.0,0,21,2025-11-07,115.0,November,2025,327902,2025-10-01
2,1097487,Heritage Magic in Merivale,4993285.0,Paulette,Christchurch City,Fendalton Ward,-43.511490,172.625400,Private room,166.0,...,1970-01-01 00:00:00.000000002,1.0,221,14,2025-11-07,249.0,November,2025,322200,2025-10-01
3,1339647508906377362,Settle into the sun set,54299306.0,Sarena,Christchurch City,Burwood Ward,-43.482864,172.668660,Entire home/apt,NaN,...,1970-01-01 00:00:00.000000000,1.0,0,2,2025-11-07,195.0,November,2025,321302,2025-10-01
4,1211070132323635531,Eco Spa-bath Studio,179297759.0,Peng,Christchurch City,Riccarton Ward,-43.538437,172.578953,Private room,126.0,...,1970-01-01 00:00:00.000000000,20.0,359,5,2025-11-07,251.0,November,2025,322700,2025-10-01

In [91]:
merged_SQL= pd.read_sql_query("""
    SELECT
        a.*,
        b.*
    FROM dataset1 AS a
    LEFT JOIN dataset2 AS b
        ON a.area_code = b.area_code
        AND a.TimeFrame = b.TimeFrame
""", conn)

In [93]:
merged_SQL.info()

<class 'pandas.DataFrame'>
RangeIndex: 19368 entries, 0 to 19367
Data columns (total 35 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              19368 non-null  int64
 1   name                            19368 non-null  str
 2   host_id                         19368 non-null  float64
 3   host_name                       19367 non-null  str
 4   neighbourhood_group             19368 non-null  str
 5   neighbourhood                   19368 non-null  str
 6   latitude                        19368 non-null  float64
 7   longitude                       19368 non-null  float64
 8   room_type                       19368 non-null  str
 9   price                           18128 non-null  float64
 10  minimum_nights                  19359 non-null  float64
 11  number_of_reviews               19368 non-null  int64
 12  last_review                     17674 non-null  str
 13  reviews_per_month               17674 non-null  str
 14  calculated_host_listings_count  19368 non-null  float64
 15  availability_365                19368 non-null  int64
 16  number_of_reviews_ltm           19368 non-null  int64
 17  Pub_date                        19368 non-null  str
 18  Difference_date                 17674 non-null  float64
 19  month_name                      19368 non-null  str
 20  year                            19368 non-null  int64
 21  area_code                       19368 non-null  int64
 22  TimeFrame                       19368 non-null  str
 23  TimeFrame                       14722 non-null  str
 24  area_code                       14722 non-null  float64
 25  Dwelling Type                   14722 non-null  str
 26  Number Of Beds                  14722 non-null  str
 27  Total Bonds                     14722 non-null  float64
 28  Active Bonds                    14722 non-null  float64
 29  Closed Bonds                    14722 non-null  float64
 30  Median Rent                     14722 non-null  float64
 31  Geometric Mean Rent             14722 non-null  float64
 32  Upper Quartile Rent             14722 non-null  float64
 33  Lower Quartile Rent             14722 non-null  float64
 34  Log Std Dev Weekly Rent         14722 non-null  float64
dtypes: float64(16), int64(6), str(13)
memory usage: 5.2 MB